/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   sv_errlist.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: gbourgeo <gbourgeo@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/01/01 01:35:48 by gbourgeo          #+#    #+#             */
/*   Updated: 2023/01/01 01:48:11 by gbourgeo         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stddef.h>
#include "err_list.h"

err_list_t	g_err_list[] = {
/* 400 */ { ERR_NOT_DEFINED, NULL },
/* 401 */ { ERR_NOSUCHNICK, "%s :No such nick" },
/* 402 */ { ERR_NOSUCHSERVER, ":No such server" },
/* 403 */ { ERR_NOSUCHCHANNEL, "%s :No such channel" },
/* 404 */ { ERR_CANNOTSENDTOCHAN, "%s :Cannot send to channel" },
/* 405 */ { ERR_TOOMANYCHANNELS, ":You have joined too many channels" },
/* 406 */ { ERR_WASNOSUCHNICK, ":There was no such nickname" },
/* 407 */ { ERR_TOOMANYTARGETS, "%s :Too many recipients. abort" },
/* 408 */ { ERR_NOSUCHSERVICE, ":No such service" },
/* 409 */ { ERR_NOORIGIN, ":No origin specified" },
/* 410 */ { ERR_NOT_DEFINED, NULL },
/* 411 */ { ERR_NORECIPIENT, ":No recipient given (%s)" },
/* 412 */ { ERR_NOTEXTTOSEND, ":No text to send" },
/* 413 */ { ERR_NOTOPLEVEL, ":No toplevel domain specified" },
/* 414 */ { ERR_WILDTOPLEVEL, ":Wildcard in toplevel domain" },
/* 415 */ { ERR_BADMASK, ":Bad Server/host mask" },
/* 416 */ { ERR_NOT_DEFINED, NULL },
/* 417 */ { ERR_NOT_DEFINED, NULL },
/* 418 */ { ERR_NOT_DEFINED, NULL },
/* 419 */ { ERR_NOT_DEFINED, NULL },
/* 420 */ { ERR_NOT_DEFINED, NULL },
/* 421 */ { ERR_UNKNOWNCOMMAND, "%s :Unknown command" },
/* 422 */ { ERR_NOMOTD, ":MOTD file is missing" },
/* 423 */ { ERR_NOADMININFO, ":No administrative info available" },
/* 424 */ { ERR_FILEERROR, ":File error..." },
/* 425 */ { ERR_NOT_DEFINED, NULL },
/* 426 */ { ERR_CREATECHANNELFAIL, "%s :Server failed to create your channel" },
/* 427 */ { ERR_NOT_DEFINED, NULL },
/* 428 */ { ERR_NOT_DEFINED, NULL },
/* 429 */ { ERR_NOT_DEFINED, NULL },
/* 430 */ { ERR_NOT_DEFINED, NULL },
/* 431 */ { ERR_NONICKNAMEGIVEN, "%s :No nickname given" },
/* 432 */ { ERR_ERRONEUSNICKNAME, "%s :Erroneus nickname" },
/* 433 */ { ERR_NICKNAMEINUSE, "%s :Nickname is already in use" },
/* 434 */ { ERR_NOT_DEFINED, NULL },
/* 435 */ { ERR_NOT_DEFINED, NULL },
/* 436 */ { ERR_NICKCOLLISION, ":Nickname collision" },
/* 437 */ { ERR_UNAVAILABLERESOURCE, ":Nick/channel is temporarily unavailable" },
/* 438 */ { ERR_NOT_DEFINED, NULL },
/* 439 */ { ERR_NOT_DEFINED, NULL },
/* 440 */ { ERR_NOT_DEFINED, NULL },
/* 441 */ { ERR_USERNOTINCHANNEL, "%s :They aren't on that channel %s" },
/* 442 */ { ERR_NOTONCHANNEL, "%s :You're not on that channel" },
/* 443 */ { ERR_USERONCHANNEL, ":is already on channel" },
/* 444 */ { ERR_NOLOGIN, ":User not logged in" },
/* 445 */ { ERR_SUMMONDISABLED, ":SUMMON has been disabled" },
/* 446 */ { ERR_USERDISABLED, ":USERS has been disbled" },
/* 447 */ { ERR_NOT_DEFINED, NULL },
/* 448 */ { ERR_NOT_DEFINED, NULL },
/* 449 */ { ERR_NOT_DEFINED, NULL },
/* 450 */ { ERR_NOT_DEFINED, NULL },
/* 451 */ { ERR_NOTREGISTERED, ":You have not registered" },
/* 452 */ { ERR_NOT_DEFINED, NULL },
/* 453 */ { ERR_NOT_DEFINED, NULL },
/* 454 */ { ERR_NOT_DEFINED, NULL },
/* 455 */ { ERR_NOT_DEFINED, NULL },
/* 456 */ { ERR_NOT_DEFINED, NULL },
/* 457 */ { ERR_NOT_DEFINED, NULL },
/* 458 */ { ERR_NOT_DEFINED, NULL },
/* 459 */ { ERR_NOT_DEFINED, NULL },
/* 460 */ { ERR_NOT_DEFINED, NULL },
/* 461 */ { ERR_NEEDMOREPARAMS, "%s :Not enough parameters" },
/* 462 */ { ERR_ALREADYREGISTERED, ":Unauthorized command (already registered)" },
/* 463 */ { ERR_NOPERMFORHOST, ":Your host isn't among the privileged" },
/* 464 */ { ERR_PASSWDMISMATCH, ":Password incorrect" },
/* 465 */ { ERR_YOUREBANNEDCREEP, ":You are banned from this server" },
/* 466 */ { ERR_YOUWILLBEBANNED, ":You will be banned soon" },
/* 467 */ { ERR_KEYSET, ":Channel key already set" },
/* 468 */ { ERR_NOT_DEFINED, NULL },
/* 469 */ { ERR_NOT_DEFINED, NULL },
/* 470 */ { ERR_NOT_DEFINED, NULL },
/* 471 */ { ERR_CHANNELISFULL, "%s :Cannot join channel (+l)" },
/* 472 */ { ERR_UNKNOWNMODE, "%s :is unknown mode char to me for %s" },
/* 473 */ { ERR_INVITEONLYCHAN, ":Cannot join channel (+i)" },
/* 474 */ { ERR_BANNEDFROMCHAN, ":Cannot join channel (+b)" },
/* 475 */ { ERR_BADCHANNELKEY, "%s :Cannot join channel (+k)" },
/* 476 */ { ERR_BADCHANMASK, ":Bad channel mask" },
/* 477 */ { ERR_NOCHANMODES, "%s :Channel doesn't support modes" },
/* 478 */ { ERR_BANLISTFULL, ":Channel list is full" },
/* 479 */ { ERR_ILLEGALNAME, "%s :Illegal channel name" },
/* 480 */ { ERR_NOT_DEFINED, NULL },
/* 481 */ { ERR_NOPRIVILEGES, "%s :Permission Denied- You're not an IRC operator" },
/* 482 */ { ERR_CHANOPRIVSNEEDED, "%s :You're not channel operator" },
/* 483 */ { ERR_CANTKILLSERVER, ":You can't kill a server!" },
/* 484 */ { ERR_RESTRICTED, ":Your connection is restricted!" },
/* 485 */ { ERR_UNIQOPPRIVSNEEDED, ":You're not the original channel operator" },
/* 486 */ { ERR_NOT_DEFINED, NULL },
/* 487 */ { ERR_NOT_DEFINED, NULL },
/* 488 */ { ERR_NOT_DEFINED, NULL },
/* 489 */ { ERR_NOT_DEFINED, NULL },
/* 490 */ { ERR_NOT_DEFINED, NULL },
/* 491 */ { ERR_NOOPERHOST, ":No appropriate operator blocks for your host" },
/* 492 */ { ERR_NOT_DEFINED, NULL },
/* 493 */ { ERR_NOT_DEFINED, NULL },
/* 494 */ { ERR_NOT_DEFINED, NULL },
/* 495 */ { ERR_NOT_DEFINED, NULL },
/* 496 */ { ERR_NOT_DEFINED, NULL },
/* 497 */ { ERR_NOT_DEFINED, NULL },
/* 498 */ { ERR_NOT_DEFINED, NULL },
/* 499 */ { ERR_NOT_DEFINED, NULL },
/* 500 */ { ERR_NOT_DEFINED, NULL },
/* 501 */ { ERR_UMODEUNKNOWNFLAG, ":Unknown MODE flag" },
/* 502 */ { ERR_USERSDONTMATCH, ":Cannot change mode for other users" },
/* 503 */ { ERR_USERSMODE, ":Cannot view mode for other users" },
};

size_t		g_err_list_size = sizeof(g_err_list) / sizeof(g_err_list[0]);